service: vatsim-data

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

custom:
  bucket: vatsim-data-${opt:stage, self:provider.stage}

functions:
  store:
    handler: handler.store
    environment:
      BUCKET: ${self:custom.bucket}
