service: vatsim-data

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.bucket}/*

custom:
  bucket: vatsim-data-${opt:stage, self:provider.stage}
  stage: ${opt:stage, self:provider.stage}
  prd:
    schedule:
      rate: rate(1 minute)
  dev:
    schedule:

functions:
  store:
    handler: handler.store
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - schedule: ${self:custom.${self:custom.stage}.schedule}
