frameworkVersion: "^2.1.0"

service: vatsimData

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.bucket}/*
  deploymentBucket:
    name: serverless-${self:provider.stage}-therailroad
    blockPublicAccess: true
    serverSideEncryption: AES256
  logRetentionInDays: ${self:custom.${self:provider.stage}.logRetentionInDays}

custom:
  bucket: vatsim-data-${self:provider.stage}-therailroad
  prod:
    schedule:
      enabled: true
      name: ${self:service}-schedule
      rate: rate(1 minute)
    logRetentionInDays: 7
  dev:
    schedule:
      enabled: false
      name: ${self:service}-schedule
      rate: rate(1 minute)
    logRetentionInDays: 7

functions:
  store:
    handler: handler.store
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - schedule: ${self:custom.${self:provider.stage}.schedule}
